Makefile, docker/Dockerfile.ubi.amd64, docker/scripts/auto-unseal.sh, docker/scripts/entrypoint.sh, docker/scripts/renewToken.sh
=> Issue3 - updated vault key

Makefile, plugin/auth_agbot.go, plugin/auth_user.go
=> Issue 7 - Adjust token lease configuration

plugin/policy.go
=> Issue 9 - Support kv v2 backend

plugin/auth_user.go
Signed-off-by: Doug Larson <larsond@us.ibm.com>
=> Issue_12 Enable plugin for iamapikeys

plugin/policy.go
Signed-off-by: Isabel Gan <Isabel.Gan@ibm.com>
=> Issue 15 - Policy does not allow users to read secret details

Makefile, docker/Dockerfile.ubi.amd64
Signed-off-by: Ben Courliss <bencourliss@ibm.com>
=> Added VAULT_PLUGIN_HASH as ENV var for container.

plugin/backend.go, plugin/config.go
=> Issue 17 - enable plugin to use SSL for vault APIs

plugin/auth_user.go
Signed-off-by: Isabel Gan <Isabel.Gan@ibm.com>
=> Issue 2675 (anax) - Vault needs to use the user ID passed from the Exchange on iamapikey authentication

docker/Dockerfile.ubi.amd64, docker/scripts/auto-unseal.sh
=> Add tar and hide logging of unseal keys

plugin/policy.go
Signed-off-by: Isabel Gan <Isabel.Gan@ibm.com>
=> Issue 2737 (anax) - Vault permissions for organization admins need to be fixed

plugin/policy.go
Signed-off-by: linggao <linggao@us.ibm.com>
=> Issue 25 - non-root user cannot list a specific org level secret

plugin/policy.go
=> Issue 27 - recreate ACLs on every login

Makefile
Signed-off-by: Ben Courliss <bencourliss@ibm.com>
=> Updated versions for next release: 1.1.0

go.mod
Signed-off-by: Jeff Kinard <jeff@thekinards.com>
=> Issue 39 - upgrade to go 1.17

Makefile
Signed-off-by: Ben Courliss <bencourliss@ibm.com>
=> Updated to latest Vault version

docker/Dockerfile.ubi.amd64
Signed-off-by: Doug Larson <larsond@us.ibm.com>
=> Issue42 - user needs to be in root group

Makefile
=> Updated to latest version of Vault

.github/workflows/build-push.yml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Added command to purge all old docker and moby dependencies before installing the updated versions.
Fixes #62
=> Issue #62 - Bug: CI Workflow failing due to Docker update step.

.github/workflows/build-push.yml, Makefile
Also added new workflow_dispatch to allow building as needed
=> Updated to use latest 1.14.8 Vault. 

.github/workflows/build-push.yml, .github/workflows/release.yaml
References: #84 
Changes:
- Adding missing GitHub workflow changes.
=> Issue 84: Adding missing GitHub workflow changes.

CHANGELOG.md, Makefile, cmd/vault-plugin-auth-openhorizon/main.go
Reference: #84
Changes:
- Fixed typo in module reference.
=> Issue 84: Fixed typo in module reference.

.github/workflows/build-push.yml, CHANGELOG.md, Makefile, go.mod, go.sum
**Vulnerability CVE-2025-27144**
**github.com/go-jose/go-jose/v4-v4.0.1**
**Description:**
https://github.com/open-horizon/vault-exchange-auth/issues/85
Go JOSE provides an implementation of the Javascript Object Signing and Encryption set of standards in Go, including support for JSON Web Encryption (JWE), JSON Web Signature (JWS), and JSON Web Token (JWT) standards. In versions on the 4.x branch
**Fix:**
```
Upgrade to version v4.0.5
The reported vulnerability was not checked for vulnerability effectiveness and is suggested to be examined using Effective Usage Analysis.
```
**Vulnerability CVE-2025-22869**
**golang.org/x/crypto-v0.31.0**
**Description:**
https://github.com/open-horizon/vault-exchange-auth/issues/86
SSH servers which implement file transfer protocols are vulnerable to a …
=> Fix vulnerabilities CVE-2025-27144/CVE-2025-22869
